### ISSUE TITLE
'Create Airtable record' only takes strings?

### ISSUE THREAD

**Issue by frisonl** [cassab/Mallard#5]
Hi, thanks for the plugin, very handy. One issue: Whenever I have a column in AirTable with numeric values (int or float or currency) and also with boolean values the component gives success as feedback, but a blank line is added in AirTable. Could it be that the component only takes strings? or am I missing something?

Thanks

**Comment by NickCassab** [comment]
yes, you're absolutely right, I'm reviewing this right now and it appears that strings, record links, and image attachments are the only 'types' that are accepted right now. I'm going to see if I can add this feature sometime soon. It should be reasonably straight forward.

**Comment by frisonl** [comment]
Ah, good to hear. Hope it is not too much trouble. Thanks!
