### ISSUE TITLE
Issues with maximum record download

### ISSUE THREAD

**Issue by Kai-Zhu-RI** [cassab/Mallard#6]
Hello Nick,

This is a fantastic plugin and very glad that you have made it open source. 

I am testing the plugin on an Airtable base with approx 7000 records and have noticed some inconsistent results when using the ListAirtableRecordsGH component. As I refresh, the number of records flowing through the GH script increases at inconsistent intervals (from 500, 900, 1400, etc.).  Ideally, I would like to spit out the maximum number of records in my base in one go. 

I know that the airtable uses pagination and their documentation says a max of 100 records per page and they give back the offset in their server response. 

I've looked through your code and it seems like you are handling this in the do while loop? I haven't had a chance to debug myself but am letting you know in this github issue.

Regards,

Kai

**Comment by NickCassab** [comment]
Hi Kai,

Thank you! I figured out how to loop through the pagination results, but I can't figure out why the results are coming back inconsistent. I think the plugin is sending multiple api requests, and it may not be waiting long enough for the Async operation to complete.

Have a go at trying to debug it! I would love some help with this thing, haha.

**Comment by Kai-Zhu-RI** [comment]
Yes I think you are right. Their documentation says max 5 requests per second which I think might be causing it:
https://community.airtable.com/t/get-all-records-from-table/45554/8

For reference, it looks like Gui's python airtable wrapper manages to get all records at once. I will take a look and see if I can debug and send a PR. Perhaps a 1 second timer per 5 calls is needed so we don't get locked out. 

https://stackoverflow.com/questions/48998254/getting-more-than-100-records-with-airtable
https://airtable-python-wrapper.readthedocs.io/en/master/api.html?highlight=get%20all#airtable.Airtable.get_all
https://github.com/gtalarico/pyairtable/blob/main/pyairtable/api/api.py#L128
https://medium.com/@gtalarico/using-airtable-as-a-content-backend-e373cd0d9974

Cheers,

**Comment by NickCassab** [comment]
Thanks for digging into this! I will also do some digging and see what I come up with. I'm familiar with Gui's work, I've thought of rewriting mallard to use his python library instead...

**Comment by NickCassab** [comment]
I just added a line that "awaits" for 300 milliseconds, I tried it on a base of mine that had 205 records and it worked, but for some reason I had to disconnect one of the wires and reattach it to get it to run. See if that works, and let me know.

**Comment by Kai-Zhu-RI** [comment]
Thanks for checking that out. I tested out your edits on my machine but it's still having issues. I also increased the time to 1 second just to see if that would help. I haven't had the time yet to take a good look into this but I will dig into this properly very soon. Will let you know how I go.

Cheers,

**Comment by NickCassab** [comment]
ok, try the latest.

I'm still experiencing some issues when the connection gets interrupted, the component will throw an error. Just refresh the toggle until it pulls down all the records correctly.

**Comment by Kai-Zhu-RI** [comment]
Hi Nick,

Still doesn't seem to be working on my end... strange. 

I did take a closer look and attempted to rewrite the async function to be recursive on my own fork of Mallard. The idea would be:

1. Make an asynchronous call to Airtable to api
2. Await the response
3. Add records to global records list
4. If response.Offset = null. Stop as this is the base case of the function.
5. If response.Offset != null. Make another recursive call to the function with the new offset as input.

It didn't work though and I am still debugging. I think it may be because of the use of a global variable to store the responses on line 24 which may be causing the issue:

        public List<Object> records = new List<object>();

Apparently using public variables with async calls is a bit risky. It might be better to put those global variables into a static class instead and read/write to them as properties. 

https://www.arclab.com/en/kb/csharp/global-variables-fields-functions-static-class.html
